server:
  servlet:
    application-display-name: tubby-front
    context-path: /
  port: 9000
  compression:
    enabled: true
    mime-types: application/javascript,application/json,text/css,text/html,text/plain
    min-response-size: 4096

logging:
  config: classpath:logback-spring.xml

spring:
  name: tubby
  main.banner-mode: "off"
  profiles:
    active: dev
  messages: 
    basename: i18n/messages
  data:
    rest:
      base-path: /api
      default-page-size: 10
  jackson:
#    time-zone: GMT+8
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"

shell:
  auth.simple.user:
    name: user
    password: ENC(Ecw1B3LnY8X8zE02fL1WL34EOvZlw0jp) #password

endpoints:
  enabled: false
  health.enabled: true

management:
  context-path: /manage

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: /auth
      refresh: /refresh

multipart:
  maxFileSize: 2048MB
  maxRequestSize: 2048MB

upload:
  baseSaveDir: /tmp

jasypt:
  encryptor:
    password: 123456

#rest超时配置
rest:
  read-timeout: 5000
  connect-timeout: 5000
  retry-count: 3

#dialect
dialect:
  database-type: mysql

---
spring:
  profiles: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost/tubby
    username: tubby
    password: tubby
    connectionTestQuery: 'SELECT 1'

---
spring:
  profiles: prod
  jpa:
    show-sql: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost/tubby
    username: tubby
    password: tubby
    connectionTestQuery: 'SELECT 1'
    max-active: 10
    max-idle: 3
    min-idle: 3
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1
    time-between-eviction-runs-millis: 300000
    min-evictable-idle-time-millis: 1800000
